version: '3'
services:
  postgres:
    image: postgres:10.5
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"

  redis:
    image: redis:4.0
    ports:
      - "6379:6379"
