# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/ruby:2.6.0-preview3-node
        environment:
          RAILS_ENV: test
          BUNDLE_PATH: vendor/bundle
          DB_HOST: localhost
          PORT: 3000
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
          REDIS_URL: redis://localhost:6379/12
      - image: postgres:10.5
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
      - image: redis:4.0

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-bundle-{{ checksum "Gemfile.lock" }}
          - v1-dependencies-bundle-

      - run:
          name: bundle install
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-bundle-{{ checksum "Gemfile.lock" }}

      - restore_cache:
          keys:
          - v1-dependencies-yarn-{{ checksum "yarn.lock" }}
          - v1-dependencies-yarn-

      - run:
          name: yarn install
          command: |
            yarn install --cache-folder ~/.cache/yarn

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: v1-dependencies-yarn-{{ checksum "yarn.lock" }}

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run: bundle exec rails db:create
      - run: bundle exec rails db:schema:load

      - run: bundle exec rake test
